---
- name: Общие действия
  hosts: all
  become: yes
  roles:
    - general_actions

- name: Настройка fail2ban и postgresql
  hosts: Host-A
  become: yes
  roles:
    - postgresql_deploy
    - fail2ban_deploy

- name: Настройка nginx и бэкапирования
  hosts: Host-B
  become: yes
  roles:
    - nginx_deploy
    - backup_postgresql

- name: Перезапуск sshd, чтобы применить настройки
  hosts: all
  become: yes
  tasks:
    - name: .
      service: "name=sshd state=restarted"
